/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import Interfaz.Arbitros.PanelArbitro;

/**
 *
 * @author nuria
 */
public class Panel extends javax.swing.JPanel {

    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BotonArbitros = new javax.swing.JButton();
        BotonJugadores = new javax.swing.JButton();
        BotonParticipaciones = new javax.swing.JButton();
        BotonParti = new javax.swing.JButton();
        BotonPueblos = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("¿Que desea gestionar?");

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("¡Bienvenido a FútbolGest!");

        BotonArbitros.setText("Árbitros");
        BotonArbitros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonArbitrosActionPerformed(evt);
            }
        });

        BotonJugadores.setText("Jugadores");
        BotonJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonJugadoresActionPerformed(evt);
            }
        });

        BotonParticipaciones.setText("Participaciones");
        BotonParticipaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonParticipacionesActionPerformed(evt);
            }
        });

        BotonParti.setText("Partidos");
        BotonParti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPartiActionPerformed(evt);
            }
        });

        BotonPueblos.setText("Pueblos");
        BotonPueblos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPueblosActionPerformed(evt);
            }
        });

        BotonSalir.setBackground(new java.awt.Color(255, 0, 51));
        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotonPueblos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonJugadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonArbitros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonParti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonParticipaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(164, 164, 164))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(BotonSalir)
                            .addGap(24, 24, 24)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonArbitros)
                .addGap(18, 18, 18)
                .addComponent(BotonJugadores)
                .addGap(18, 18, 18)
                .addComponent(BotonParticipaciones)
                .addGap(18, 18, 18)
                .addComponent(BotonParti)
                .addGap(18, 18, 18)
                .addComponent(BotonPueblos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(BotonSalir)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed

        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void BotonPueblosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPueblosActionPerformed
        Interfaz.Pueblos.PanelPueblo p = new Interfaz.Pueblos.PanelPueblo();
        p.setVisible(true);
    }//GEN-LAST:event_BotonPueblosActionPerformed

    private void BotonPartiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPartiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonPartiActionPerformed

    private void BotonParticipacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonParticipacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonParticipacionesActionPerformed

    private void BotonJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonJugadoresActionPerformed
        // TODO add your handling code here:
        Interfaz.Jugadores.PanelJugador jg = new Interfaz.Jugadores.PanelJugador();
        jg.setVisible(true);
    }//GEN-LAST:event_BotonJugadoresActionPerformed

    private void BotonArbitrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonArbitrosActionPerformed
        // TODO add your handling code here:
       Interfaz.Arbitros.PanelArbitro panelArb = new PanelArbitro();
       panelArb.setVisible(true);
    }//GEN-LAST:event_BotonArbitrosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonArbitros;
    private javax.swing.JButton BotonJugadores;
    private javax.swing.JButton BotonParti;
    private javax.swing.JButton BotonParticipaciones;
    private javax.swing.JButton BotonPueblos;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
