/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Views.Participaciones;

import Controladores.JugadorDAO;
import Controladores.ParticipacionDAO;
import Controladores.PartidoDAO;
import Entitys.Arbitro;
import Entitys.Jugador;
import Entitys.Participacion;
import Entitys.Partido;
import java.awt.HeadlessException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author nuria
 */
public class CrearParticipacion extends javax.swing.JDialog {

    /**
     * Creates new form CrearArbitro
     */
    private JugadorDAO jugadorDAO = new JugadorDAO();
    private PartidoDAO partidoDAO = new PartidoDAO();

    public CrearParticipacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarPartidos();
        cargarJugadores();
    }

    private void cargarPartidos() {
        List<Partido> listaPartido = partidoDAO.listarTodos();
        for (Partido a : listaPartido) {
            PartidoParticipa.addItem(a);
        }
    }

    private void cargarJugadores() {
        List<Jugador> listaJugador = jugadorDAO.listarTodos();
        for (Jugador a : listaJugador) {
            JugadorParticipa.addItem(a);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CrearParticipacion = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Goles =  new javax.swing.JSpinner(new SpinnerNumberModel(0, 0, Integer.MAX_VALUE, 1));
        PartidoParticipa = new javax.swing.JComboBox<>();
        JugadorParticipa = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Jugador que participa: ");

        CrearParticipacion.setText("Crear");
        CrearParticipacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearParticipacionActionPerformed(evt);
            }
        });

        Salir.setBackground(new java.awt.Color(255, 0, 0));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        jLabel2.setText("Goles que marcó:");

        jLabel3.setText("Partido en el que participó:");

        PartidoParticipa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PartidoParticipaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                        .addGap(181, 181, 181))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CrearParticipacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Salir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Goles, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JugadorParticipa, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PartidoParticipa, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addComponent(JugadorParticipa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(PartidoParticipa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(Goles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CrearParticipacion)
                    .addComponent(Salir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearParticipacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearParticipacionActionPerformed
        try {
            Jugador jugador = (Jugador) JugadorParticipa.getSelectedItem();
            Partido partido = (Partido) PartidoParticipa.getSelectedItem();
            int goles = (Integer) Goles.getValue();

            if (jugador == null || partido == null) {
                JOptionPane.showMessageDialog(this, "Selecciona un jugador y un partido.");
                return;
            }

            Participacion participacion = new Participacion();
            participacion.setJugador(jugador);
            participacion.setPartido(partido);
            participacion.setGoles(goles);
            if (goles < 0) {
                JOptionPane.showMessageDialog(this, "Los goles no pueden ser negativos.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            ParticipacionDAO participacionDAO = new ParticipacionDAO();
            participacionDAO.crear(participacion);

            JOptionPane.showMessageDialog(this, "Participación creada correctamente.");
            dispose();

        } catch (HeadlessException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al crear participación: " + e.getMessage());
        }
    }//GEN-LAST:event_CrearParticipacionActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
dispose();     }//GEN-LAST:event_SalirActionPerformed

    private void PartidoParticipaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PartidoParticipaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PartidoParticipaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearParticipacion;
    private javax.swing.JSpinner Goles;
    private javax.swing.JComboBox<Jugador> JugadorParticipa;
    private javax.swing.JComboBox<Partido> PartidoParticipa;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
