/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Views.Participaciones;

import Controladores.JugadorDAO;
import Controladores.ParticipacionDAO;
import Controladores.PartidoDAO;
import Entitys.Jugador;
import Entitys.Participacion;
import Entitys.Partido;
import java.awt.HeadlessException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author nuria
 */
public class EditarParticipacion extends javax.swing.JDialog {

    /**
     * Creates new form CrearArbitro
     */
    private ParticipacionDAO participacionDAO = new ParticipacionDAO();
    private Participacion participacionActual;
    private JugadorDAO jugadorDAO = new JugadorDAO();
    private PartidoDAO partidoDAO = new PartidoDAO();

    public EditarParticipacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarPartidos();
        cargarJugadores();
    }

    private void cargarPartidos() {
        List<Partido> listaPartido = partidoDAO.listarTodos();
        for (Partido a : listaPartido) {
            PartidoParticipa.addItem(a);
        }
    }

    private void cargarJugadores() {
        List<Jugador> listaJugador = jugadorDAO.listarTodos();
        for (Jugador a : listaJugador) {
            JugadorParticipa.addItem(a);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        editarPart = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Goles = new javax.swing.JSpinner(new SpinnerNumberModel(0, 0, Integer.MAX_VALUE, 1));
        PartidoParticipa = new javax.swing.JComboBox<>();
        JugadorParticipa = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Jugador que participa: ");

        editarPart.setText("Editar");
        editarPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarPartActionPerformed(evt);
            }
        });

        Salir.setBackground(new java.awt.Color(255, 0, 0));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        jLabel2.setText("Goles que marcó:");

        jLabel3.setText("Partido en el que participó:");

        PartidoParticipa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PartidoParticipaActionPerformed(evt);
            }
        });

        jLabel4.setText("ID de la participación: ");

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                        .addGap(181, 181, 181))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editarPart)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Salir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Goles, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JugadorParticipa, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PartidoParticipa, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscar)
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar))
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addComponent(JugadorParticipa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(PartidoParticipa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(Goles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarPart)
                    .addComponent(Salir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editarPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarPartActionPerformed
        if (participacionActual != null) {

            Jugador jugadorSeleccionado = (Jugador) JugadorParticipa.getSelectedItem();
            Partido partidoSeleccionado = (Partido) PartidoParticipa.getSelectedItem();
            int golesMarcados = (int) Goles.getValue();

            
            participacionActual.setJugador(jugadorSeleccionado);
            participacionActual.setPartido(partidoSeleccionado);
           
            participacionActual.setGoles(golesMarcados);

            if (golesMarcados < 0) {
            JOptionPane.showMessageDialog(this, "Los goles no pueden ser negativos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
            
            
            participacionDAO.actualizar(participacionActual);
            JOptionPane.showMessageDialog(this, "Participación actualizada correctamente.");

        } else {
            JOptionPane.showMessageDialog(this, "Debe buscar una participación para editar primero.");

        }
    }//GEN-LAST:event_editarPartActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
dispose();     }//GEN-LAST:event_SalirActionPerformed

    private void PartidoParticipaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PartidoParticipaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PartidoParticipaActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed

        try {
            int participacionId = Integer.parseInt(id.getText().trim());

            ParticipacionDAO participacionDAO = new ParticipacionDAO();
            Participacion participacion = participacionDAO.leer(participacionId);

            if (participacion == null) {
                JOptionPane.showMessageDialog(this, "No se encontró ninguna participación con ese ID.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            for (int i = 0; i < JugadorParticipa.getItemCount(); i++) {
                if (JugadorParticipa.getItemAt(i).getId() == participacion.getJugador().getId()) {
                    JugadorParticipa.setSelectedIndex(i);
                    break;
                }
            }

            for (int i = 0; i < PartidoParticipa.getItemCount(); i++) {
                if (PartidoParticipa.getItemAt(i).getId() == participacion.getPartido().getId()) {
                    PartidoParticipa.setSelectedIndex(i);
                    break;
                }
            }
            Goles.setValue(participacion.getGoles());

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Introduce un ID válido.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Error al buscar la participación: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buscarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Goles;
    private javax.swing.JComboBox<Jugador> JugadorParticipa;
    private javax.swing.JComboBox<Partido> PartidoParticipa;
    private javax.swing.JButton Salir;
    private javax.swing.JButton buscar;
    private javax.swing.JButton editarPart;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
