/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Views.Partidos;

import Controladores.ArbitroDAO;
import Controladores.PartidoDAO;
import Entitys.Arbitro;
import Entitys.Partido;
import java.awt.HeadlessException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author nuria
 */

public class CrearPartido extends javax.swing.JDialog {

    /**
     * Creates new form CrearArbitro
     */
    
    private ArbitroDAO arbitroDAO = new ArbitroDAO();
    
    public CrearPartido(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    cargarArbitros();
    }

   private void cargarArbitros() {
    List<Arbitro> listaArbitros = arbitroDAO.listarTodos(); 
    for (Arbitro a : listaArbitros) {
        Arbitros.addItem(a);
    }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lugarCrear = new javax.swing.JTextField();
        CrearPartido = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Arbitros = new javax.swing.JComboBox<>();
        fechaCrear = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Fecha del partido a crear: ");

        lugarCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lugarCrearActionPerformed(evt);
            }
        });

        CrearPartido.setText("Crear");
        CrearPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearPartidoActionPerformed(evt);
            }
        });

        Salir.setBackground(new java.awt.Color(255, 0, 0));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        jLabel2.setText("Arbitro del partido:");

        jLabel3.setText("Lugar del partido a crear: ");

        fechaCrear.setText("yyyy-MM-dd");
        fechaCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lugarCrear)
                        .addGap(105, 105, 105))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Arbitros, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                        .addGap(181, 181, 181))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CrearPartido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Salir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fechaCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(fechaCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lugarCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(Arbitros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CrearPartido)
                    .addComponent(Salir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lugarCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lugarCrearActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_lugarCrearActionPerformed

    private void CrearPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearPartidoActionPerformed
       try {
        Date fechaPartido = new SimpleDateFormat("yyyy-MM-dd").parse(fechaCrear.getText());
        String lugar = lugarCrear.getText();
        Arbitro arbitroSeleccionado = (Arbitro) Arbitros.getSelectedItem();
        Partido nuevoPartido = new Partido();
        nuevoPartido.setFecha(fechaPartido);
        nuevoPartido.setLugar(lugar);
        nuevoPartido.setArbitro(arbitroSeleccionado);

        PartidoDAO partidoDAO = new PartidoDAO();
        partidoDAO.crear(nuevoPartido); 

        JOptionPane.showMessageDialog(this, "Partido creado correctamente.");
        dispose();

    } catch (HeadlessException | ParseException e) {
        JOptionPane.showMessageDialog(this, "Error al crear el partido: " + e.getMessage());
    }
    }//GEN-LAST:event_CrearPartidoActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
dispose();     }//GEN-LAST:event_SalirActionPerformed

    private void fechaCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaCrearActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Arbitro> Arbitros;
    private javax.swing.JButton CrearPartido;
    private javax.swing.JButton Salir;
    private javax.swing.JTextField fechaCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField lugarCrear;
    // End of variables declaration//GEN-END:variables
}
