/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Views.Partidos;

import Controladores.ArbitroDAO;
import Controladores.PartidoDAO;
import Entitys.Arbitro;
import Entitys.Partido;
import java.awt.HeadlessException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author nuria
 */
public class EditarPartido extends javax.swing.JDialog {

    /**
     * Creates new form CrearArbitro
     */
    private PartidoDAO partDAO = new PartidoDAO();
    private Partido partidoActual;
    private ArbitroDAO arbitroDAO = new ArbitroDAO();

    public EditarPartido(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarArbitros();
    }

    private void cargarArbitros() {
        List<Arbitro> listaArbitros = arbitroDAO.listarTodos();
        for (Arbitro a : listaArbitros) {
            Arbitros.addItem(a);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lugarEditar = new javax.swing.JTextField();
        EditarPartido = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Arbitros = new javax.swing.JComboBox<>();
        fechaEditar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        idBuscar = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Fecha del partido: ");

        lugarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lugarEditarActionPerformed(evt);
            }
        });

        EditarPartido.setText("Editar");
        EditarPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarPartidoActionPerformed(evt);
            }
        });

        Salir.setBackground(new java.awt.Color(255, 0, 0));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        jLabel2.setText("Arbitro del partido:");

        jLabel3.setText("Lugar del partido: ");

        fechaEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaEditarActionPerformed(evt);
            }
        });

        jLabel4.setText("Id del partido a editar:");

        idBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idBuscarActionPerformed(evt);
            }
        });

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lugarEditar)
                        .addGap(105, 105, 105))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                        .addGap(181, 181, 181))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EditarPartido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Salir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Arbitros, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaEditar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(idBuscar))
                        .addGap(18, 18, 18)
                        .addComponent(Buscar)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(fechaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(lugarEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(Arbitros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditarPartido)
                    .addComponent(Salir))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lugarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lugarEditarActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_lugarEditarActionPerformed

    private void EditarPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarPartidoActionPerformed
        try {
            if (partidoActual != null) {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

                Date nuevaFecha = sdf.parse(fechaEditar.getText());
                String nuevoLugar = lugarEditar.getText();
                Arbitro nuevoArbitro = (Arbitro) Arbitros.getSelectedItem();

                partidoActual.setFecha(nuevaFecha);
                partidoActual.setLugar(nuevoLugar);
                partidoActual.setArbitro(nuevoArbitro);

                partDAO.actualizar(partidoActual);

                JOptionPane.showMessageDialog(this, "Partido actualizado correctamente.");
            } else {
                JOptionPane.showMessageDialog(this, "Primero busca un partido para editar.");
            }
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Formato de fecha incorrecto. Usa yyyy-MM-dd.");
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar el partido.");
            e.printStackTrace(); 
        }
    }//GEN-LAST:event_EditarPartidoActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
dispose();     }//GEN-LAST:event_SalirActionPerformed

    private void fechaEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaEditarActionPerformed

    private void idBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idBuscarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:   
        try {
            int id = Integer.parseInt(idBuscar.getText());
            partidoActual = partDAO.leer(id);

            if (partidoActual != null) {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                fechaEditar.setText(sdf.format(partidoActual.getFecha()));

                lugarEditar.setText(partidoActual.getLugar());
                Arbitros.setSelectedItem(partidoActual.getArbitro());

            } else {
                JOptionPane.showMessageDialog(this, "Partido no encontrado.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID inválido.");
        }
    }//GEN-LAST:event_BuscarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Arbitro> Arbitros;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton EditarPartido;
    private javax.swing.JButton Salir;
    private javax.swing.JTextField fechaEditar;
    private javax.swing.JTextField idBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField lugarEditar;
    // End of variables declaration//GEN-END:variables
}
