/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz.Arbitros;

/**
 *
 * @author nuria
 */
public class PanelArbitros extends javax.swing.JPanel {

    /**
     * Creates new form PanelArbitros
     */
    public PanelArbitros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        EditarArb = new javax.swing.JButton();
        CrearArb = new javax.swing.JButton();
        BorrarARb = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        ListarArb = new javax.swing.JButton();

        jLabel1.setText("¿Qué desea hacer?");

        EditarArb.setText("Editar");
        EditarArb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarArbActionPerformed(evt);
            }
        });

        CrearArb.setText("Crear");
        CrearArb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearArbActionPerformed(evt);
            }
        });

        BorrarARb.setText("Borrar");
        BorrarARb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarARbActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        ListarArb.setText("Listar");
        ListarArb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarArbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Salir)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ListarArb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BorrarARb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditarArb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(CrearArb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(163, 163, 163))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EditarArb)
                .addGap(18, 18, 18)
                .addComponent(CrearArb)
                .addGap(18, 18, 18)
                .addComponent(BorrarARb)
                .addGap(18, 18, 18)
                .addComponent(ListarArb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(Salir)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CrearArbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearArbActionPerformed
        // TODO add your handling code here:
        CrearArbitro crearArbitro = new CrearArbitro(null, true);
        crearArbitro.setVisible(true);
    }//GEN-LAST:event_CrearArbActionPerformed

    private void EditarArbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarArbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditarArbActionPerformed

    private void BorrarARbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarARbActionPerformed
        // TODO add your handling code here:
        BorrarArbitro borrarArbitro = new BorrarArbitro(null, true);
        borrarArbitro.setVisible(true);
    }//GEN-LAST:event_BorrarARbActionPerformed

    private void ListarArbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarArbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListarArbActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:

        System.exit(0);

    }//GEN-LAST:event_SalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BorrarARb;
    private javax.swing.JButton CrearArb;
    private javax.swing.JButton EditarArb;
    private javax.swing.JButton ListarArb;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
